language: java
jdk:
- oraclejdk8

sudo: required
services:
  - docker

env:
  - SPRING_REDIS_PORT=6379
  - SPRING_REDIS_HOST=localhost

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

jobs:
  include:
  - stage: frontend
    script: docker run pachecopaulo/react-test npm test -- --coverage
    before_script:
      - docker build -t pachecopaulo/react-test -f ./client/Dockerfile.dev ./client
  - stage: lint
    script: ./gradlew lintKotlin
  - stage: test
    script: ./gradlew test
    before_script:
      - docker run --name redis-test-db -p 6379:6379 -d redis
    after_success:
      - docker build -t pachecopaulo/multi-client ./client
      - docker build -t pachecopaulo/multi-nginx ./nginx
      - docker build -t pachecopaulo/multi-server .
  - stage: docker_hub_authentication
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - stage: pushImage
    script:
      - docker push pachecopaulo/multi-client
      - docker push pachecopaulo/multi-nginx
      - docker push pachecopaulo/multi-server
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/