language: java
jdk:
- oraclejdk8

sudo: required
services:
  - docker

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

jobs:
  include:
  - stage: Frontend Build
    script: docker run pachecopaulo/react-test npm test -- --coverage
    before_script:
      - docker build -t pachecopaulo/react-test -f ./client/Dockerfile.dev ./client
  - stage: Lint
    script: ./gradlew lintKotlin
#  - stage: Backend Test
#    script: ./gradlew test
#    before_script:
#      - docker run --name redis-test-db -p 6379:6379 -d redis
  - stage: Build and Push Images
    script:
      - docker build -t pachecopaulo/multi-client ./client
      - docker build -t pachecopaulo/multi-nginx ./nginx
      - docker build -t pachecopaulo/multi-server .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - docker push pachecopaulo/multi-client
      - docker push pachecopaulo/multi-nginx
      - docker push pachecopaulo/multi-server
      - docker push pachecopaulo/multi-server
  - stage: Deploy
    script: skip
    deploy:
      provider: elasticbeanstalk
      region: "eu-west-2"
      app: "fibonacci-multidocker"
      env: "FibonacciMultidocker-env"
      bucket_name: "elasticbeanstalk-eu-west-2-160364560450"
      bucket_path: "docker-multi"
      on:
        branch: master
      access_key_id: "$AWS_ACCESS_KEY"
      secret_access_key:
        secure: "$AWS_SECRET_KEY"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/